model:
  name: newnet
  num_classes: 3
  in_channels: 1
  init_filters: 4

training:
  batch_size: 8
  epochs: 200
  optimizer:
    name: 'adam'
    lr: 1e-3
    weight_decay: 0
  scheduler:
    name: 'CosineAnnealingLR'
    t_max: 200
    lr_max: 1e-3
    lr_min: 1e-4

data:
  trainval_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/trainval.csv'     
  test_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/test.csv'    
  augmentation:
    - random_flip:
        p: 0.5
    - random_affine:
        p: 1
        degrees: 0
        scales: [1, 1.5]
      translation: 0
    - random_affine:
        p: 1
        degrees: 0
        scales: [0.66, 1]
        translation: 0

cross_validation:
  method: holdout
  folds: 5