model:
  name: resnet18
  num_classes: 3
  in_channels: 1
  init_filters: 4

training:
  batch_size: 8
  epochs: 200
  optimizer:
    name: 'adam'
    lr: 1e-3
    weight_decay: 0
  scheduler:
    name: 'CosineAnnealingLR'
    t_max: 200
    lr_max: 1e-3
    lr_min: 1e-4

data:
  trainval_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2_crop/data/trainval.csv'     
  test_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2_crop/data/test.csv'    
  augmentation:
    - random_flip:
        p: 0.5
    - random_affine:
        p: 0.3
        degrees: 0
        translation: 5
        scales: 0
        
cross_validation:
  method: kfold
  folds: 5