training:
  batch_size: 16
  epochs: 150
  optimizer:
    name: adamw
    weight_decay: 0.01
    lr: 0.0001
    patience: 10
  scheduler:
    name: CosineAnnealingLR
    t_max: 150
    lr_max: 0.001
    lr_min: 1.0e-06
data:
  trainval_csv: /project/aereditato/cestari/adni-mri-classification/data/preprocessing_mri_pet/datasets/dataset_unimodal_pet_trainval.csv
  test_csv: /project/aereditato/cestari/adni-mri-classification/data/preprocessing_mri_pet/datasets/dataset_unimodal_pet_test.csv
  classes:  # AD vs MCI
    - 2
    - 3
  augmentation:
    - random_flip:
        p: 0.5
    - random_affine:
        p: 0.5
        degrees: 5
        translation: 5
    - random_noise:
        p: 0.2
        std: 0.02
  oversample: false
cross_validation:
  method: kfold
  folds: 5
  val_fraction: 0.2
  seed: 42
model:
  name: resnet18
  num_classes: 2
  in_channels: 1
  init_filters: 8
  dropout: 0.3
