model:
  name: resnet18
  num_classes: 2
  in_channels: 1
  init_filters: 16
  dropout: 0.25

training:
  batch_size: 16
  epochs: 150
  optimizer:
    name: 'adamw'
    lr: 1e-4
    weight_decay: 1e-2
    patience: 10
  scheduler:
    name: 'CosineAnnealingLR'
    
    t_max: 150
    lr_max: 1e-3
    lr_min: 1e-6

data:
  trainval_csv: '/project/aereditato/abhat/adni-mri-classification/data/preprocessing_dicom_spm_2/trainval_MCI_vs_AD.csv'     
  test_csv: '/project/aereditato/abhat/adni-mri-classification/data/preprocessing_dicom_spm_2/test_MCI_vs_AD.csv'    
  augmentation:
    random_flip:
      p: 0.5
    random_affine:
      p: 0.5
      degrees: 5
      translation: 5
    random_noise:
      p: 0.2
      std: 0.02
  oversample: false

cross_validation:
  method: kfold
  folds: 5
  seed: 42