model:
  depth: 
  activation:
  pool:
  norm:
  kernel_size:
  dropout: 0
  num_classes: 3
  name: simple_3dcnn
  in_channels: 1
  init_filters: 8

training:
  batch_size: 32
  epochs: 200
  optimizer:
    name: 'adam'
    weight_decay: 0
    lr: 1e-4
  scheduler:
    name: 'CosineAnnealingLR'
    t_max: 200
    lr_max: 1e-4
    lr_min: 2e-6

cross_validation:
  method: 'holdout'
  val_frac: 0.1

data:
  trainval_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/trainval.csv'     
  test_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/test.csv'    
  oversample: false
  cutmix: 
    p: 1
  augmentation:
    - random_flip:
        p: 0.5

